### ISSUE TITLE
NAT and cluster end up in different zones, put in same zone

### ISSUE THREAD

**Issue by viglesiasce** [danisla/terraform-google-k8s-gce#3]
I am seeing the NAT box in us-central1-f and the rest of the cluster in us-central1-b.

**Comment by danisla** [comment]
This was in the example repo, fixed by copying the region and zone info of the cluster to the nat gateway module. https://github.com/danisla/terraform-google-examples/commit/f4d61ccf88784b11d79456984111f89651af0815
